### ISSUE TITLE
Need help fixing a crash issue

### ISSUE THREAD

**Issue by Spectral-Dreams** [ineedbots/bo1_bot_warfare#19]
@ineedbots

ok, there's a bit of an issue with 2 maps, round based modes, and bots. The maps are berlin wall and convoy; they both cause a CTD on the second round. I was using the latest version of the Bot Warfare mod. Funnily enough, I sort of know how to fix this. The fix is in the Black Frontlines mod. It's a code snippet in there. I'm no coder, so is someone willing to take a look at that code snippet in that mod and integrate it into Bot Warfare?

Here's the black frontlines mod, you'll need to extract the ff file (I don't have BO1 or the mod tools installed ATM, so I forgot where exactly the fix was, but just open the one of the .gsc files or w/e and look for berlinwall and you'll find the code snippets)
https://www.moddb.com/mods/black-frontlines/downloads/black-frontlines-10

IIRC, the way that mod fixed the issue was to despawn the bots and then respawn them on the next round. It should hopefully be easy to integrate into Bot Warfare.

Moreover, I do recall sharing this exact same fix and code snippet with you years ago on discord. I think you either didn't bother fixing the issue or forgot, maybe?

Thanks!

**Comment by ineedbots** [comment]
Plutonium should be fixing this issue in their next release.

The issue is with the disconnect path function in gsc, basically, when its called it will disconnect the path for the bots and dogs, and when its called it will try to kill the bot's pathing if their path contains the link, but the problem is, it does this at the very first frame of the game starting, and players do not have an entity.
